name: Release

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  # Build package on commits to main.
  build:
    name: Build & verify package
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      id-token: write
    outputs:
      package-version: ${{ steps.baipp.outputs.package_version }}
      package-name: ${{ steps.baipp.outputs.package_name }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2
        id: baipp
        with:
          attest-build-provenance-github: 'true'

  # Publish to pypi.org on tagged commit on main.
  publish-pypi:
    name: Publish to pypi.org
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: publish-pypi
      url: https://pypi.org/project/${{ needs.build.outputs.package-name }}/${{ needs.build.outputs.package-version }}
    if: |
      github.repository_owner == 'tahv'
      && github.event_name == 'push'
      && startsWith(github.ref, 'refs/tags')
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: Packages
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true

  # Upload to test.pypi.org on every commit on main.
  publish-test-pypi:
    name: Publish to test.pypi.org
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: publish-test-pypi
      url: https://test.pypi.org/project/${{ needs.build.outputs.package-name }}/${{ needs.build.outputs.package-version }}
    if: |
      github.repository_owner == 'tahv'
      && github.event_name == 'push'
      && github.ref == 'refs/heads/main'
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: Packages
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
          repository-url: https://test.pypi.org/legacy/

  # Draft a new release on tagged commits on main.
  draft-release:
    name: Draft release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: Packages
          path: dist
      - uses: astral-sh/setup-uv@v7
      - run: >
          uv run --no-project scripts/release-notes.py
          --version "${{ github.ref_name }}"
          --diff-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/compare/{old}...{new}"
          > RELEASE.md
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          body_path: RELEASE.md
          files: dist/*
